# -*- coding: utf-8 -*-
"""22_클래스 상속.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hkj07jLwOPiUFSkenbMzzO-J05WZ_vFa

덧셈, 뺄셈 기능이 있는 클래스를 만들고, 이를 상속하는 클래스를 만들어서 곱셈과 나눗셈 기능을 추가해보자.
"""

class CalculatorSuper:

  def add(self, n1, n2):
    return n1 + n2

  def sub(self, n1, n2):
    return n1 - n2

class CalculatorChild(CalculatorSuper):

  def mul(self, n1, n2):
    return n1 * n2

  def div(self, n1, n2):
    return n1 / n2

cal = CalculatorChild()

print(f'cal.add(10, 20): {cal.add(10, 20)}')
print(f'cal.sub(10, 20): {cal.sub(10, 20)}')
print(f'cal.mul(10, 20): {cal.mul(10, 20)}')
print(f'cal.div(10, 20): {cal.div(10, 20)}')